<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="kssbot" params="prefix">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>

    <!-- arbitrary value for chassis value -->
    <xacro:property name="chassis_mass" value="5.0" />
    <xacro:property name="chassis_length" value="0.12" />
    <xacro:property name="chassis_width" value="0.12" />
    <xacro:property name="chassis_height" value="0.065" />
    <xacro:property name="chassis_z_offset" value="0.02" />

    <!-- arbitrary value for wheel value -->
    <xacro:property name="wheel_mass" value="0.5" /> 
    <xacro:property name="wheel_len" value="0.024" />
    <xacro:property name="wheel_radius" value="0.035" />

    <!-- Space btw top of beam and the each joint -->
    <xacro:property name="z_offset" value="${chassis_height/2}" /> 

    <!-- arbitrary value for ultrasonic eye value -->
    <xacro:property name="sonic_mass" value="0.06" /> 
    <xacro:property name="sonic_len" value="0.007" />
    <xacro:property name="sonic_radius" value="0.0075" />

    <!-- arbitrary value for front camera value -->
    <xacro:property name="cam_length" value="0.02" />
    <xacro:property name="cam_width" value="0.045" />
    <xacro:property name="cam_height" value="0.033" />

    <!-- Base Link -->
    <link 
      name="base_link">
    </link>

    <!-- Base Footprint Joint -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link 
      name="base_footprint">
    </link>

    <!-- Chassis Joint -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${chassis_z_offset + z_offset}"/>
    </joint>

    <!-- Chassis Link-->
    <link name="chassis">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${chassis_mass}"/>
        <inertia
          ixx="${chassis_mass / 12.0 * (chassis_length*chassis_length + chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
          iyy="${chassis_mass / 12.0 * (chassis_height*chassis_height + chassis_width*chassis_width)}" iyz="0.0"
          izz="${chassis_mass / 12.0 * (chassis_width*chassis_width + chassis_length*chassis_length)}"/>
      </inertial>
    </link>

    <!-- left wheel Joint -->
    <joint name="left_wheel_joint" type="continuous">
      <parent link="chassis"/>
      <child link="left_wheel"/>
      <origin xyz="0.035 ${chassis_width/2 + wheel_len/2} ${chassis_z_offset-wheel_radius}" rpy="-${PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- left wheel Link -->
    <link name="left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius* wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3*wheel_radius* wheel_radius + wheel_len*wheel_len)}" iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
      </inertial>

    </link>

    <!-- left wheel dummy Joint -->
    <joint name="left_wheel_dummy_joint" type="fixed">
      <parent link="chassis"/>
      <child link="left_wheel_dummy"/>
      <origin xyz="-0.055 ${chassis_width/2 + wheel_len/2} ${chassis_z_offset-wheel_radius}" rpy="-${PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- left wheel dummy Link -->
    <link name="left_wheel_dummy">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius* wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3*wheel_radius* wheel_radius + wheel_len*wheel_len)}" iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
        </inertial>
    </link>

    <!-- right wheel Joint -->
    <joint name="right_wheel_joint" type="continuous">
      <parent link="chassis"/>
      <child link="right_wheel"/>
      <origin xyz="0.035 -${chassis_width/2 + wheel_len/2} ${chassis_z_offset-wheel_radius}" rpy="${PI/2} 0 0"/>
      <axis xyz="0 0 -1"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- right wheel Link -->
    <link name="right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius* wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3*wheel_radius* wheel_radius + wheel_len*wheel_len)}" iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
        </inertial>

    </link>

    <!-- right wheel dummy Joint -->
    <joint name="right_wheel_dummy_joint" type="fixed">
      <parent link="chassis"/>
      <child link="right_wheel_dummy"/>
      <origin xyz="-0.055 -${chassis_width/2 + wheel_len/2} ${chassis_z_offset-wheel_radius}" rpy="${PI/2} 0 0"/>
      <axis xyz="0 0 -1"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- right wheel dummy Link -->
    <link name="right_wheel_dummy">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius* wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3*wheel_radius* wheel_radius + wheel_len*wheel_len)}" iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
        </inertial>
    </link>

    <!-- left ultrasonic eye Joint -->
    <joint name="left_ultrasonic_eye_joint" type="fixed">
      <parent link="chassis"/>
      <child link="left_ultrasonic_eye"/>
      <origin xyz="0.06 0.0125 -0.0125" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- left ultrasonic eye Link -->
    <link name="left_ultrasonic_eye">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="0.007" radius="0.0075"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder length="${sonic_len}" radius="${sonic_radius}"/>
        </geometry>
        <material name="grey"/>
      </visual>

    </link>

    <!-- right ultrasonic eye Joint -->
    <joint name="right_ultrasonic_eye_joint" type="fixed">
      <parent link="chassis"/>
      <child link="right_ultrasonic_eye"/>
      <origin xyz="0.06 -0.0125 -0.0125" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- right ultrasonic eye Link -->
    <link name="right_ultrasonic_eye">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${sonic_len}" radius="${sonic_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder length="0.007" radius="0.0075"/>
        </geometry>
        <material name="grey"/>
      </visual>

    </link>


    <!-- front camera Joint -->
    <joint name="front_camera_joint" type="fixed">
      <parent link="chassis"/>
      <child link="front_camera"/>
      <origin xyz="0.06 0 0.0225" rpy="0 0 0"/>
    </joint>

    <!-- front camera Link -->
    <link name="front_camera">

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${cam_length} ${cam_width} ${cam_height}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${cam_length} ${cam_width} ${cam_height}"/>
        </geometry>
        <material name="red"/>
      </visual>

    </link>
    
  </xacro:macro>

</robot>
